package com.example.demo.bean;

import java.math.BigDecimal;
import java.util.Date;

/**
 * Created by zft on 2017/7/10.
 */
public class UserBean {

    private String id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.name
     *
     * @mbggenerated
     */
    private String name;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.phone
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.pwd
     *
     * @mbggenerated
     */
    private String pwd;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.sex
     *
     * @mbggenerated
     */
    private Integer sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.icon_server_url
     *
     * @mbggenerated
     */
    private String iconServerUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.icon_path_url
     *
     * @mbggenerated
     */
    private String iconPathUrl;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.birthday
     *
     * @mbggenerated
     */
    private String birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.hobby
     *
     * @mbggenerated
     */
    private String hobby;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.education
     *
     * @mbggenerated
     */
    private Integer education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.industry
     *
     * @mbggenerated
     */
    private String industry;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.city_id
     *
     * @mbggenerated
     */
    private String cityId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.district_id
     *
     * @mbggenerated
     */
    private String districtId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.money
     *
     * @mbggenerated
     */
    private BigDecimal money;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.is_del
     *
     * @mbggenerated
     */
    private Integer isDel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.has_unread_msg
     *
     * @mbggenerated
     */
    private Integer hasUnreadMsg;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.invite_phone
     *
     * @mbggenerated
     */
    private String invitePhone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.add_date
     *
     * @mbggenerated
     */
    private Date addDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.qq_name
     *
     * @mbggenerated
     */
    private String qqName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.openid_qq
     *
     * @mbggenerated
     */
    private String openidQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.weibo_name
     *
     * @mbggenerated
     */
    private String weiboName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.openid_weibo
     *
     * @mbggenerated
     */
    private String openidWeibo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.weixin_name
     *
     * @mbggenerated
     */
    private String weixinName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.openid_weixin
     *
     * @mbggenerated
     */
    private String openidWeixin;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.source
     *
     * @mbggenerated
     */
    private Integer source;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.site_id
     *
     * @mbggenerated
     */
    private String siteId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.cash_on_delivery
     *
     * @mbggenerated
     */
    private Integer cashOnDelivery;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.is_show
     *
     * @mbggenerated
     */
    private Integer isShow;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_user.bonuspoint
     *
     * @mbggenerated
     */
    private Integer bonuspoint;


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getPwd() {
        return pwd;
    }

    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    public Integer getSex() {
        return sex;
    }

    public void setSex(Integer sex) {
        this.sex = sex;
    }

    public String getIconServerUrl() {
        return iconServerUrl;
    }

    public void setIconServerUrl(String iconServerUrl) {
        this.iconServerUrl = iconServerUrl;
    }

    public String getIconPathUrl() {
        return iconPathUrl;
    }

    public void setIconPathUrl(String iconPathUrl) {
        this.iconPathUrl = iconPathUrl;
    }

    public String getBirthday() {
        return birthday;
    }

    public void setBirthday(String birthday) {
        this.birthday = birthday;
    }

    public String getHobby() {
        return hobby;
    }

    public void setHobby(String hobby) {
        this.hobby = hobby;
    }

    public Integer getEducation() {
        return education;
    }

    public void setEducation(Integer education) {
        this.education = education;
    }

    public String getIndustry() {
        return industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public String getCityId() {
        return cityId;
    }

    public void setCityId(String cityId) {
        this.cityId = cityId;
    }

    public String getDistrictId() {
        return districtId;
    }

    public void setDistrictId(String districtId) {
        this.districtId = districtId;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public BigDecimal getMoney() {
        return money;
    }

    public void setMoney(BigDecimal money) {
        this.money = money;
    }

    public Integer getIsDel() {
        return isDel;
    }

    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    public Integer getHasUnreadMsg() {
        return hasUnreadMsg;
    }

    public void setHasUnreadMsg(Integer hasUnreadMsg) {
        this.hasUnreadMsg = hasUnreadMsg;
    }

    public String getInvitePhone() {
        return invitePhone;
    }

    public void setInvitePhone(String invitePhone) {
        this.invitePhone = invitePhone;
    }

    public Date getAddDate() {
        return addDate;
    }

    public void setAddDate(Date addDate) {
        this.addDate = addDate;
    }

    public String getQqName() {
        return qqName;
    }

    public void setQqName(String qqName) {
        this.qqName = qqName;
    }

    public String getOpenidQq() {
        return openidQq;
    }

    public void setOpenidQq(String openidQq) {
        this.openidQq = openidQq;
    }

    public String getWeiboName() {
        return weiboName;
    }

    public void setWeiboName(String weiboName) {
        this.weiboName = weiboName;
    }

    public String getOpenidWeibo() {
        return openidWeibo;
    }

    public void setOpenidWeibo(String openidWeibo) {
        this.openidWeibo = openidWeibo;
    }

    public String getWeixinName() {
        return weixinName;
    }

    public void setWeixinName(String weixinName) {
        this.weixinName = weixinName;
    }

    public String getOpenidWeixin() {
        return openidWeixin;
    }

    public void setOpenidWeixin(String openidWeixin) {
        this.openidWeixin = openidWeixin;
    }

    public Integer getSource() {
        return source;
    }

    public void setSource(Integer source) {
        this.source = source;
    }

    public String getSiteId() {
        return siteId;
    }

    public void setSiteId(String siteId) {
        this.siteId = siteId;
    }

    public Integer getCashOnDelivery() {
        return cashOnDelivery;
    }

    public void setCashOnDelivery(Integer cashOnDelivery) {
        this.cashOnDelivery = cashOnDelivery;
    }

    public Integer getIsShow() {
        return isShow;
    }

    public void setIsShow(Integer isShow) {
        this.isShow = isShow;
    }

    public Integer getBonuspoint() {
        return bonuspoint;
    }

    public void setBonuspoint(Integer bonuspoint) {
        this.bonuspoint = bonuspoint;
    }
}
